version: '3.8'

services:
  postgres_user:
    image: postgres:latest
    container_name: user_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: ms_user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres_email:
    image: postgres:latest
    container_name: email_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: ms_email_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_email_data:/var/lib/postgresql/data

volumes:
  postgres_user_data:
  postgres_email_data: